In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

## Reading Dataa

In [3]:
col_names = ['Season', 'Age', 'Child Diseases', 'Accident', 'Surgical intervention', 'High fevers', 'Alcohol consumption', 'Smoking habit',
            'hours spent sitting', 'Diagnosis']
data = pd.read_csv('fertility_Diagnosis.txt', names= col_names)
data.head()

Season   Age  Child Diseases  Accident  Surgical intervention  High fevers  \
0   -0.33  0.69               0         1                      1            0   
1   -0.33  0.94               1         0                      1            0   
2   -0.33  0.50               1         0                      0            0   
3   -0.33  0.75               0         1                      1            0   
4   -0.33  0.67               1         1                      0            0   

   Alcohol consumption  Smoking habit  hours spent sitting Diagnosis  
0                  0.8              0                 0.88         N  
1                  0.8              1                 0.31         O  
2                  1.0             -1                 0.50         N  
3                  1.0             -1                 0.38         N  
4                  0.8             -1                 0.50         O

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Season                 100 non-null    float64
 1   Age                    100 non-null    float64
 2   Child Diseases         100 non-null    int64  
 3   Accident               100 non-null    int64  
 4   Surgical intervention  100 non-null    int64  
 5   High fevers            100 non-null    int64  
 6   Alcohol consumption    100 non-null    float64
 7   Smoking habit          100 non-null    int64  
 8   hours spent sitting    100 non-null    float64
 9   Diagnosis              100 non-null    object 
dtypes: float64(4), int64(5), object(1)
memory usage: 7.9+ KB


## Data Processing

In [9]:
X = data.drop('Diagnosis', axis=1)
y = pd.DataFrame(data['Diagnosis'])
y.shape

(100, 1)

In [10]:
from sklearn.preprocessing import LabelEncoder

In [11]:
le = LabelEncoder()
y = le.fit_transform(y)

C:\Users\John\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [13]:
y

array([0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0])

In [14]:
np.bincount(y)

array([88, 12], dtype=int64)

In [15]:
from sklearn.model_selection import train_test_split

In [17]:
X = X.values

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,stratify=y, random_state=101)

In [24]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [25]:
from sklearn.linear_model import LogisticRegression

In [26]:
lgr_model = LogisticRegression()
lgr_model.fit(X_train, y_train)

LogisticRegression()

In [27]:
lgr_pred = lgr_model.predict(X_test)

In [28]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [29]:
print('-----Confusion Matrix-----')
print(confusion_matrix(y_test, lgr_pred))
      
print('-------Classification Report--------')
print(classification_report(y_test, lgr_pred))

-----Confusion Matrix-----
[[18  0]
 [ 2  0]]
-------Classification Report--------
              precision    recall  f1-score   support

           0       0.90      1.00      0.95        18
           1       0.00      0.00      0.00         2

    accuracy                           0.90        20
   macro avg       0.45      0.50      0.47        20
weighted avg       0.81      0.90      0.85        20



C:\Users\John\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\John\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\John\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [30]:
accuracy_score(y_test, lgr_pred)

0.9

## The Above results does not depict the actual performance of the model since the dataset is bias to class - 0 (normal fertility)